import bcryptjs from "bcryptjs";
import { Book, Category, Brand, Address, User, GiftPoints } from "./types";

export const categories: Category[] = [
  { id: "cat-1", name: "All", slug: "all" },
  { id: "cat-2", name: "Romance", slug: "romance" },
  { id: "cat-3", name: "Mystery", slug: "mystery" },
  { id: "cat-4", name: "Science Fiction", slug: "science-fiction" },
  { id: "cat-5", name: "Fantasy", slug: "fantasy" },
  { id: "cat-6", name: "Historical", slug: "historical" },
  { id: "cat-7", name: "Biography", slug: "biography" },
  { id: "cat-8", name: "Self-help", slug: "self-help" },
  { id: "cat-9", name: "Memoir", slug: "memoir" },
  { id: "cat-10", name: "Travel", slug: "travel" },
  { id: "cat-11", name: "Cooking", slug: "cooking" },
  { id: "cat-12", name: "Children's", slug: "childrens" },
  { id: "cat-13", name: "Young Adult", slug: "young-adult" },
  { id: "cat-14", name: "Comics & Graphic Novels", slug: "comics-graphic-novels" },
  { id: "cat-15", name: "Poetry", slug: "poetry" },
  { id: "cat-16", name: "Drama", slug: "drama" },
  { id: "cat-17", name: "Science", slug: "science" },
  { id: "cat-18", name: "Philosophy", slug: "philosophy" },
  { id: "cat-19", name: "Religion", slug: "religion" },
  { id: "cat-20", name: "Language Learning", slug: "language-learning" },
];

export const brands: Brand[] = [
  {
    id: "brand-1",
    name: "Penguin Random House",
    slug: "penguin-random-house",
    description: "The premier global publisher of books, literature, and educational materials.",
  },
  {
    id: "brand-2",
    name: "HarperCollins",
    slug: "harpercollins",
    description: "One of the world's largest entertainment and publishing leaders.",
  },
  {
    id: "brand-3",
    name: "Pan Macmillan",
    slug: "pan-macmillan",
    description: "Renowned international publisher of award-winning fiction and non-fiction.",
  },
  {
    id: "brand-4",
    name: "Oxford University Press",
    slug: "oxford-university-press",
    description: "World-leading academic publisher fostering scholarly excellence across all disciplines.",
  },
];

export const books: Book[] = [
  {
    id: "b-1",
    title: "Shadows in the Mist",
    author: "Eleanor Vance",
    authorId: "auth-1",
    category: "Mystery",
    brand: "Penguin Random House",
    format: "Paperback",
    price: 499,
    imageUrl: "https://picsum.photos/seed/b-1/200/300",
    stock: 25,
    deliveryDays: 3,
    description: "A chilling tale set in a secluded coastal village where every secret holds a price.",
    tagline: "Some secrets are better left buried under the fog.",
    tags: ["Crime", "Thriller", "Suspense"],
    relatedIds: ["b-2", "b-3", "b-4"],
    bestseller: true,
    newLaunch: false,
    sells: 1420,
    language: "English",
    rating: 4.8,
    authorBio: "Eleanor Vance is a bestselling crime novelist based in Edinburgh.",
    authorAvatar: "https://picsum.photos/seed/auth-1/100/100",
    reviews: [
      { id: "r-1-1", reviewer: "Jane Doe", text: "Unputdownable from page one! Gripping atmosphere.", rating: 5, date: "2024-01-15" },
      { id: "r-1-2", reviewer: "Mark Ross", text: "A clever mystery with unexpected twists.", rating: 4.5, date: "2024-02-02" },
    ],
  },
  {
    id: "b-2",
    title: "The Midnight Cipher",
    author: "David Sterling",
    authorId: "auth-2",
    category: "Mystery",
    brand: "HarperCollins",
    format: "Hardcover",
    price: 699,
    imageUrl: "https://picsum.photos/seed/b-2/200/300",
    stock: 18,
    deliveryDays: 2,
    description: "Cryptanalysts race against time to decode a WWII artifact holding modern global consequences.",
    tagline: "The clock strikes twelve. The code unlocks everything.",
    tags: ["Codebreaking", "Espionage", "Historical"],
    relatedIds: ["b-1", "b-7", "b-15"],
    bestseller: true,
    newLaunch: false,
    sells: 2150,
    language: "English",
    rating: 4.7,
    authorBio: "David Sterling is a former intelligence analyst turned thriller author.",
    authorAvatar: "https://picsum.photos/seed/auth-2/100/100",
    reviews: [
      { id: "r-2-1", reviewer: "Alice Kim", text: "Fast-paced, brilliant technical depth.", rating: 5, date: "2024-01-10" },
      { id: "r-2-2", reviewer: "Robert Chen", text: "Kept me guessing right up to the end.", rating: 4.5, date: "2024-02-18" },
    ],
  },
  {
    id: "b-3",
    title: "Whispers of the Heart",
    author: "Clara Hawthorne",
    authorId: "auth-3",
    category: "Romance",
    brand: "Pan Macmillan",
    format: "Paperback",
    price: 399,
    imageUrl: "https://picsum.photos/seed/b-3/200/300",
    stock: 30,
    deliveryDays: 4,
    description: "Two estranged musicians reunite in Vienna during an unforgettable winter season.",
    tagline: "Music brought them together; fate tore them apart.",
    tags: ["Contemporary", "Music", "Drama"],
    relatedIds: ["b-4", "b-11", "b-12"],
    bestseller: true,
    newLaunch: false,
    sells: 3400,
    language: "English",
    rating: 4.9,
    authorBio: "Clara Hawthorne writes heartwarming contemporary romance and poetry.",
    authorAvatar: "https://picsum.photos/seed/auth-3/100/100",
    reviews: [
      { id: "r-3-1", reviewer: "Emily Watson", text: "Cried happy tears. Such a tender love story.", rating: 5, date: "2024-02-14" },
      { id: "r-3-2", reviewer: "Liam Brown", text: "Lyrical writing and deep emotional resonance.", rating: 4.8, date: "2024-02-20" },
    ],
  },
  {
    id: "b-4",
    title: "Autumn in Tuscany",
    author: "Clara Hawthorne",
    authorId: "auth-3",
    category: "Romance",
    brand: "Pan Macmillan",
    format: "Paperback",
    price: 450,
    imageUrl: "https://picsum.photos/seed/b-4/200/300",
    stock: 14,
    deliveryDays: 3,
    description: "A vineyard restoration project blossoms into an unexpected romance amidst golden Italian hills.",
    tagline: "Love is the rarest vintage of all.",
    tags: ["Italy", "Wine", "Feel-Good"],
    relatedIds: ["b-3", "b-10", "b-19"],
    bestseller: false,
    newLaunch: true,
    sells: 890,
    language: "English",
    rating: 4.6,
    authorBio: "Clara Hawthorne writes heartwarming contemporary romance and poetry.",
    authorAvatar: "https://picsum.photos/seed/auth-3/100/100",
    reviews: [
      { id: "r-4-1", reviewer: "Sarah Jenkins", text: "Pure escapism! Made me want to book a trip to Italy.", rating: 5, date: "2024-03-01" },
      { id: "r-4-2", reviewer: "Lucas Meyer", text: "Charming characters and lush descriptions.", rating: 4.2, date: "2024-03-05" },
    ],
  },
  {
    id: "b-5",
    title: "Starlight Odyssey",
    author: "Marcus Vance",
    authorId: "auth-4",
    category: "Science Fiction",
    brand: "HarperCollins",
    format: "Hardcover",
    price: 799,
    imageUrl: "https://picsum.photos/seed/b-5/200/300",
    stock: 22,
    deliveryDays: 2,
    description: "A colony ship encounters an alien megastructure at the edge of known spacetime.",
    tagline: "Beyond the stars lies an answer we weren't ready for.",
    tags: ["Space Opera", "Alien", "Hard Sci-Fi"],
    relatedIds: ["b-6", "b-17", "b-22"],
    bestseller: true,
    newLaunch: false,
    sells: 4100,
    language: "English",
    rating: 4.9,
    authorBio: "Marcus Vance is an astrophysicist and Hugo Award finalist.",
    authorAvatar: "https://picsum.photos/seed/auth-4/100/100",
    reviews: [
      { id: "r-5-1", reviewer: "Devon Reed", text: "Grand scale sci-fi at its finest. Mind-bending ideas.", rating: 5, date: "2024-01-22" },
      { id: "r-5-2", reviewer: "Elena Rostova", text: "Hard science blended with deep humanity.", rating: 4.8, date: "2024-02-12" },
    ],
  },
  {
    id: "b-6",
    title: "Quantum Paradox",
    author: "Marcus Vance",
    authorId: "auth-4",
    category: "Science Fiction",
    brand: "Penguin Random House",
    format: "Paperback",
    price: 540,
    imageUrl: "https://picsum.photos/seed/b-6/200/300",
    stock: 19,
    deliveryDays: 3,
    description: "Parallel realities begin collapsing when a physics lab creates a localized multiverse rift.",
    tagline: "Every choice creates a universe. One is coming to destroy yours.",
    tags: ["Multiverse", "Physics", "Thriller"],
    relatedIds: ["b-5", "b-17", "b-24"],
    bestseller: false,
    newLaunch: true,
    sells: 760,
    language: "English",
    rating: 4.5,
    authorBio: "Marcus Vance is an astrophysicist and Hugo Award finalist.",
    authorAvatar: "https://picsum.photos/seed/auth-4/100/100",
    reviews: [
      { id: "r-6-1", reviewer: "Samir Patel", text: "Complex and thought-provoking quantum thriller.", rating: 4.5, date: "2024-03-02" },
      { id: "r-6-2", reviewer: "Chloe Bennett", text: "High adrenaline and solid conceptual foundation.", rating: 4.5, date: "2024-03-07" },
    ],
  },
  {
    id: "b-7",
    title: "Chronicles of Eldoria",
    author: "Gwendolyn Frost",
    authorId: "auth-5",
    category: "Fantasy",
    brand: "HarperCollins",
    format: "Hardcover",
    price: 850,
    imageUrl: "https://picsum.photos/seed/b-7/200/300",
    stock: 35,
    deliveryDays: 2,
    description: "An ancient dragon pact is broken, plunging five magical realms into a war for survival.",
    tagline: "When dragons fall, darkness reigns.",
    tags: ["High Fantasy", "Magic", "Dragons"],
    relatedIds: ["b-8", "b-13", "b-14"],
    bestseller: true,
    newLaunch: false,
    sells: 5200,
    language: "English",
    rating: 4.9,
    authorBio: "Gwendolyn Frost is an epic fantasy writer and mythologist.",
    authorAvatar: "https://picsum.photos/seed/auth-5/100/100",
    reviews: [
      { id: "r-7-1", reviewer: "Arthur Pendelton", text: "Worldbuilding of Tolkien caliber. Absolute masterpiece.", rating: 5, date: "2024-01-05" },
      { id: "r-7-2", reviewer: "Mira Thorne", text: "Epic, rich in detail, unforgettable characters.", rating: 5, date: "2024-02-19" },
    ],
  },
  {
    id: "b-8",
    title: "The Rune Weaver",
    author: "Gwendolyn Frost",
    authorId: "auth-5",
    category: "Fantasy",
    brand: "Pan Macmillan",
    format: "Paperback",
    price: 480,
    imageUrl: "https://picsum.photos/seed/b-8/200/300",
    stock: 20,
    deliveryDays: 4,
    description: "A street orphan discovers she can weave elemental runes thought extinct for a millennium.",
    tagline: "Power etched in stone, destiny written in fire.",
    tags: ["Magic System", "Coming of Age", "Quest"],
    relatedIds: ["b-7", "b-13", "b-14"],
    bestseller: false,
    newLaunch: true,
    sells: 620,
    language: "English",
    rating: 4.7,
    authorBio: "Gwendolyn Frost is an epic fantasy writer and mythologist.",
    authorAvatar: "https://picsum.photos/seed/auth-5/100/100",
    reviews: [
      { id: "r-8-1", reviewer: "Kevin Zhao", text: "The magic system is fresh and uniquely crafted.", rating: 5, date: "2024-03-04" },
      { id: "r-8-2", reviewer: "Tanya Brooks", text: "Fast reading with an inspiring protagonist.", rating: 4.4, date: "2024-03-08" },
    ],
  },
  {
    id: "b-9",
    title: "Empire of Sands",
    author: "Julian Thorne",
    authorId: "auth-6",
    category: "Historical",
    brand: "Oxford University Press",
    format: "Hardcover",
    price: 720,
    imageUrl: "https://picsum.photos/seed/b-9/200/300",
    stock: 15,
    deliveryDays: 3,
    description: "The rise and fall of the Nabataean trade routes across the ancient Arabian peninsula.",
    tagline: "Silk, spice, and sandstone kings.",
    tags: ["Ancient History", "Middle East", "Trade"],
    relatedIds: ["b-10", "b-18", "b-23"],
    bestseller: false,
    newLaunch: false,
    sells: 1100,
    language: "English",
    rating: 4.6,
    authorBio: "Julian Thorne is a professor of ancient Mediterranean history at Oxford.",
    authorAvatar: "https://picsum.photos/seed/auth-6/100/100",
    reviews: [
      { id: "r-9-1", reviewer: "Dr. Walter Scott", text: "Meticulously researched and vividly told.", rating: 4.8, date: "2024-01-30" },
      { id: "r-9-2", reviewer: "Hannah Bell", text: "Brings ancient desert civilizations to life.", rating: 4.4, date: "2024-02-15" },
    ],
  },
  {
    id: "b-10",
    title: "The Silk Road Letters",
    author: "Julian Thorne",
    authorId: "auth-6",
    category: "Historical",
    brand: "Penguin Random House",
    format: "Paperback",
    price: 510,
    imageUrl: "https://picsum.photos/seed/b-10/200/300",
    stock: 28,
    deliveryDays: 3,
    description: "A merchant's translated travel journals navigating Chang'an to Constantinople in 1240 AD.",
    tagline: "One journey across continents and centuries.",
    tags: ["Silk Road", "Letters", "Medieval"],
    relatedIds: ["b-9", "b-18", "b-19"],
    bestseller: false,
    newLaunch: true,
    sells: 540,
    language: "English",
    rating: 4.5,
    authorBio: "Julian Thorne is a professor of ancient Mediterranean history at Oxford.",
    authorAvatar: "https://picsum.photos/seed/auth-6/100/100",
    reviews: [
      { id: "r-10-1", reviewer: "Oliver Vance", text: "Fascinating historical firsthand accounts.", rating: 4.5, date: "2024-03-01" },
      { id: "r-10-2", reviewer: "Zoe Taylor", text: "Enthralling look at medieval intercultural exchange.", rating: 4.5, date: "2024-03-06" },
    ],
  },
  {
    id: "b-11",
    title: "Mastering Focus",
    author: "Dr. Aris Thorne",
    authorId: "auth-7",
    category: "Self-help",
    brand: "Penguin Random House",
    format: "Paperback",
    price: 420,
    imageUrl: "https://picsum.photos/seed/b-11/200/300",
    stock: 50,
    deliveryDays: 2,
    description: "Neuroscience-backed principles to defeat distraction, reclaim deep attention, and thrive.",
    tagline: "Your attention is your most precious asset. Guard it.",
    tags: ["Productivity", "Mindfulness", "Neuroscience"],
    relatedIds: ["b-12", "b-20", "b-25"],
    bestseller: true,
    newLaunch: false,
    sells: 6800,
    language: "English",
    rating: 4.9,
    authorBio: "Dr. Aris Thorne is a cognitive psychologist and behavioral researcher.",
    authorAvatar: "https://picsum.photos/seed/auth-7/100/100",
    reviews: [
      { id: "r-11-1", reviewer: "Brian Cox", text: "Changed how I work every single day. Essential read.", rating: 5, date: "2024-01-18" },
      { id: "r-11-2", reviewer: "Priya Sharma", text: "Practical, actionable, zero fluff.", rating: 4.8, date: "2024-02-22" },
    ],
  },
  {
    id: "b-12",
    title: "Habits of Clarity",
    author: "Dr. Aris Thorne",
    authorId: "auth-7",
    category: "Self-help",
    brand: "HarperCollins",
    format: "Paperback",
    price: 380,
    imageUrl: "https://picsum.photos/seed/b-12/200/300",
    stock: 40,
    deliveryDays: 3,
    description: "Micro-habits to simplify mental clutter and make decisive life decisions with confidence.",
    tagline: "Small daily rituals lead to profound mental serenity.",
    tags: ["Habits", "Decision Making", "Clarity"],
    relatedIds: ["b-11", "b-20", "b-26"],
    bestseller: false,
    newLaunch: true,
    sells: 920,
    language: "English",
    rating: 4.7,
    authorBio: "Dr. Aris Thorne is a cognitive psychologist and behavioral researcher.",
    authorAvatar: "https://picsum.photos/seed/auth-7/100/100",
    reviews: [
      { id: "r-12-1", reviewer: "Nathan Drake", text: "Direct, concise, and incredibly helpful guide.", rating: 5, date: "2024-03-03" },
      { id: "r-12-2", reviewer: "Carla Gomez", text: "Helped me build positive daily morning routines.", rating: 4.4, date: "2024-03-09" },
    ],
  },
  {
    id: "b-13",
    title: "The Alchemist of Shadows",
    author: "Valerie Sterling",
    authorId: "auth-8",
    category: "Young Adult",
    brand: "Pan Macmillan",
    format: "Paperback",
    price: 360,
    imageUrl: "https://picsum.photos/seed/b-13/200/300",
    stock: 32,
    deliveryDays: 3,
    description: "A sixteen-year-old apprentice uncovers a conspiracy within the high academy of alchemy.",
    tagline: "Every spell cast casts a shadow in return.",
    tags: ["Magic Academy", "Mystery", "YA Fantasy"],
    relatedIds: ["b-7", "b-8", "b-14"],
    bestseller: true,
    newLaunch: false,
    sells: 3800,
    language: "English",
    rating: 4.8,
    authorBio: "Valerie Sterling is a bestselling Young Adult fantasy novelist.",
    authorAvatar: "https://picsum.photos/seed/auth-8/100/100",
    reviews: [
      { id: "r-13-1", reviewer: "Maya Lin", text: "Loved every single character! Couldn't put it down.", rating: 5, date: "2024-01-28" },
      { id: "r-13-2", reviewer: "Ethan Hunt", text: "Smart twists and great magical academy atmosphere.", rating: 4.6, date: "2024-02-16" },
    ],
  },
  {
    id: "b-14",
    title: "Whispers in the Library",
    author: "Valerie Sterling",
    authorId: "auth-8",
    category: "Young Adult",
    brand: "HarperCollins",
    format: "Hardcover",
    price: 520,
    imageUrl: "https://picsum.photos/seed/b-14/200/300",
    stock: 25,
    deliveryDays: 2,
    description: "Secret doors in the town library lead to the preserved memories of the departed.",
    tagline: "Some books read you back.",
    tags: ["Books", "Urban Fantasy", "Adventure"],
    relatedIds: ["b-13", "b-7", "b-15"],
    bestseller: false,
    newLaunch: true,
    sells: 810,
    language: "English",
    rating: 4.7,
    authorBio: "Valerie Sterling is a bestselling Young Adult fantasy novelist.",
    authorAvatar: "https://picsum.photos/seed/auth-8/100/100",
    reviews: [
      { id: "r-14-1", reviewer: "Lily Adams", text: "A love letter to book lovers and magical secrets.", rating: 5, date: "2024-03-02" },
      { id: "r-14-2", reviewer: "Jordan Lee", text: "Atmospheric, gentle, and utterly enchanting.", rating: 4.4, date: "2024-03-08" },
    ],
  },
  {
    id: "b-15",
    title: "Tales of the Neon City",
    author: "Kai Ren",
    authorId: "auth-9",
    category: "Comics & Graphic Novels",
    brand: "Pan Macmillan",
    format: "Paperback",
    price: 650,
    imageUrl: "https://picsum.photos/seed/b-15/200/300",
    stock: 18,
    deliveryDays: 4,
    description: "Cyberpunk detective noir rendered in vivid full-colour illustrations across Neo-Kobe.",
    tagline: "When rain falls on chrome, nothing stays pure.",
    tags: ["Cyberpunk", "Graphic Novel", "Sci-Fi"],
    relatedIds: ["b-5", "b-6", "b-16"],
    bestseller: true,
    newLaunch: false,
    sells: 2900,
    language: "English",
    rating: 4.9,
    authorBio: "Kai Ren is an award-winning graphic novelist and concept illustrator.",
    authorAvatar: "https://picsum.photos/seed/auth-9/100/100",
    reviews: [
      { id: "r-15-1", reviewer: "Alex Mercer", text: "Artwork is breathtaking! Story holds up brilliantly.", rating: 5, date: "2024-01-14" },
      { id: "r-15-2", reviewer: "Tina Fey", text: "Stunning cyberpunk atmosphere and tight narrative.", rating: 4.8, date: "2024-02-11" },
    ],
  },
  {
    id: "b-16",
    title: "Echoes of the Void",
    author: "Kai Ren",
    authorId: "auth-9",
    category: "Comics & Graphic Novels",
    brand: "Penguin Random House",
    format: "Hardcover",
    price: 890,
    imageUrl: "https://picsum.photos/seed/b-16/200/300",
    stock: 12,
    deliveryDays: 3,
    description: "A cosmic graphic novel chronicling the voyages of humanity's silent explorers.",
    tagline: "In the silence between stars, someone answered.",
    tags: ["Cosmic Horror", "Space", "Art Book"],
    relatedIds: ["b-15", "b-5", "b-6"],
    bestseller: false,
    newLaunch: true,
    sells: 470,
    language: "English",
    rating: 4.6,
    authorBio: "Kai Ren is an award-winning graphic novelist and concept illustrator.",
    authorAvatar: "https://picsum.photos/seed/auth-9/100/100",
    reviews: [
      { id: "r-16-1", reviewer: "Marcus Wright", text: "Visually stunning. Every panel is gallery-worthy.", rating: 5, date: "2024-03-01" },
      { id: "r-16-2", reviewer: "Sarah Paul", text: "Haunting and meditative graphic storytelling.", rating: 4.2, date: "2024-03-06" },
    ],
  },
  {
    id: "b-17",
    title: "The Physics of Eternity",
    author: "Dr. Evelyn Drake",
    authorId: "auth-10",
    category: "Science",
    brand: "Oxford University Press",
    format: "Hardcover",
    price: 920,
    imageUrl: "https://picsum.photos/seed/b-17/200/300",
    stock: 14,
    deliveryDays: 3,
    description: "A deep dive into thermodynamics, cosmic entropy, and what physics says about the end of time.",
    tagline: "How the universe was born and how it will quietly end.",
    tags: ["Cosmology", "Entropy", "Physics"],
    relatedIds: ["b-5", "b-6", "b-18"],
    bestseller: false,
    newLaunch: false,
    sells: 1650,
    language: "English",
    rating: 4.8,
    authorBio: "Dr. Evelyn Drake is a theoretical cosmologist and public educator.",
    authorAvatar: "https://picsum.photos/seed/auth-10/100/100",
    reviews: [
      { id: "r-17-1", reviewer: "Prof. Alan Vance", text: "Clear, lucid, and profound scientific writing.", rating: 5, date: "2024-01-20" },
      { id: "r-17-2", reviewer: "Danielle Cooper", text: "Mind-expanding exploration of our cosmic destiny.", rating: 4.6, date: "2024-02-14" },
    ],
  },
  {
    id: "b-18",
    title: "The Meditations on Being",
    author: "Soren Holst",
    authorId: "auth-11",
    category: "Philosophy",
    brand: "Oxford University Press",
    format: "Paperback",
    price: 490,
    imageUrl: "https://picsum.photos/seed/b-18/200/300",
    stock: 22,
    deliveryDays: 4,
    description: "Essays on existentialism, human agency, and modern purpose in an automated world.",
    tagline: "Finding genuine meaning when everything is simulated.",
    tags: ["Existentialism", "Ethics", "Mind"],
    relatedIds: ["b-17", "b-19", "b-27"],
    bestseller: false,
    newLaunch: false,
    sells: 1340,
    language: "English",
    rating: 4.7,
    authorBio: "Soren Holst is a Danish philosopher and author on contemporary existentialism.",
    authorAvatar: "https://picsum.photos/seed/auth-11/100/100",
    reviews: [
      { id: "r-18-1", reviewer: "Gregory House", text: "Profound and timely questions for modern society.", rating: 5, date: "2024-01-25" },
      { id: "r-18-2", reviewer: "Maria Santos", text: "Engaging philosophical reflections without heavy jargon.", rating: 4.4, date: "2024-02-27" },
    ],
  },
  {
    id: "b-19",
    title: "Wanderlust Chronicles",
    author: "Maya Lin",
    authorId: "auth-12",
    category: "Travel",
    brand: "Penguin Random House",
    format: "Paperback",
    price: 530,
    imageUrl: "https://picsum.photos/seed/b-19/200/300",
    stock: 26,
    deliveryDays: 2,
    description: "Solo backpacking adventures through remote mountain villages across the Himalayas and Andes.",
    tagline: "Not all those who wander are seeking to return.",
    tags: ["Adventure", "Mountains", "Solo Travel"],
    relatedIds: ["b-4", "b-10", "b-20"],
    bestseller: true,
    newLaunch: false,
    sells: 2800,
    language: "English",
    rating: 4.8,
    authorBio: "Maya Lin is a travel photographer, explorer, and mountaineer.",
    authorAvatar: "https://picsum.photos/seed/auth-12/100/100",
    reviews: [
      { id: "r-19-1", reviewer: "Tom Henderson", text: "Inspiring and poetic travel memoir.", rating: 5, date: "2024-01-12" },
      { id: "r-19-2", reviewer: "Clara Davis", text: "Packed with breathtaking stories and genuine warmth.", rating: 4.6, date: "2024-02-19" },
    ],
  },
  {
    id: "b-20",
    title: "Flavours of the Levant",
    author: "Chef Sami Haddad",
    authorId: "auth-13",
    category: "Cooking",
    brand: "Pan Macmillan",
    format: "Hardcover",
    price: 899,
    imageUrl: "https://picsum.photos/seed/b-20/200/300",
    stock: 16,
    deliveryDays: 3,
    description: "Traditional and modern Middle Eastern recipes celebrating family, spice, and heritage.",
    tagline: "Food is the shortest distance between two souls.",
    tags: ["Cookbook", "Middle Eastern", "Culinary"],
    relatedIds: ["b-19", "b-21", "b-28"],
    bestseller: false,
    newLaunch: true,
    sells: 710,
    language: "English",
    rating: 4.9,
    authorBio: "Chef Sami Haddad is a Michelin-starred chef based in Beirut and London.",
    authorAvatar: "https://picsum.photos/seed/auth-13/100/100",
    reviews: [
      { id: "r-20-1", reviewer: "Nadia Youssef", text: "Every recipe we tried turned out restaurant-quality!", rating: 5, date: "2024-03-02" },
      { id: "r-20-2", reviewer: "George Miller", text: "Beautiful photos and easy-to-follow directions.", rating: 4.8, date: "2024-03-07" },
    ],
  },
  {
    id: "b-21",
    title: "Songs of the Wild Sea",
    author: "Rowan Blake",
    authorId: "auth-14",
    category: "Poetry",
    brand: "Oxford University Press",
    format: "Paperback",
    price: 320,
    imageUrl: "https://picsum.photos/seed/b-21/200/300",
    stock: 30,
    deliveryDays: 2,
    description: "Verses reflecting on ocean tides, solitary lighthouses, and the rhythms of grief and hope.",
    tagline: "Where the tide ebbs, poetry begins.",
    tags: ["Ocean", "Nature", "Lyrical"],
    relatedIds: ["b-3", "b-22", "b-29"],
    bestseller: false,
    newLaunch: false,
    sells: 980,
    language: "English",
    rating: 4.7,
    authorBio: "Rowan Blake is an Irish poet and recipient of the Forward Prize.",
    authorAvatar: "https://picsum.photos/seed/auth-14/100/100",
    reviews: [
      { id: "r-21-1", reviewer: "Fiona O'Connor", text: "Deeply moving poetry that stays with you.", rating: 5, date: "2024-01-19" },
      { id: "r-21-2", reviewer: "Sean Murphy", text: "Luminous and soothing verse.", rating: 4.4, date: "2024-02-24" },
    ],
  },
  {
    id: "b-22",
    title: "The Glass Stage",
    author: "Helena Rostova",
    authorId: "auth-15",
    category: "Drama",
    brand: "HarperCollins",
    format: "Paperback",
    price: 375,
    imageUrl: "https://picsum.photos/seed/b-22/200/300",
    stock: 20,
    deliveryDays: 4,
    description: "A three-act play detailing the explosive clash inside a premier ballet company's final premiere.",
    tagline: "Perfection has a cost nobody wants to pay.",
    tags: ["Ballet", "Theatre", "Script"],
    relatedIds: ["b-3", "b-21", "b-30"],
    bestseller: false,
    newLaunch: false,
    sells: 670,
    language: "English",
    rating: 4.5,
    authorBio: "Helena Rostova is a playwright whose works have staged in West End and Broadway.",
    authorAvatar: "https://picsum.photos/seed/auth-15/100/100",
    reviews: [
      { id: "r-22-1", reviewer: "Donald Sterling", text: "Sharp dialogue and razor-sharp dramatic tension.", rating: 4.5, date: "2024-01-29" },
      { id: "r-22-2", reviewer: "Vanessa Cole", text: "Electrifying read from start to finish.", rating: 4.5, date: "2024-02-17" },
    ],
  },
  {
    id: "b-23",
    title: "The Little Dragon Who Lost His Spark",
    author: "Penny Bright",
    authorId: "auth-16",
    category: "Children's",
    brand: "HarperCollins",
    format: "Hardcover",
    price: 349,
    imageUrl: "https://picsum.photos/seed/b-23/200/300",
    stock: 45,
    deliveryDays: 2,
    description: "Ignis the baby dragon sets out on an adventure to find his roar, finding true friendship instead.",
    tagline: "Your courage shines brighter than any flame.",
    tags: ["Bedtime Story", "Dragons", "Friendship"],
    relatedIds: ["b-7", "b-13", "b-24"],
    bestseller: true,
    newLaunch: false,
    sells: 4900,
    language: "English",
    rating: 4.9,
    authorBio: "Penny Bright has illustrated and written over 20 beloved children's books.",
    authorAvatar: "https://picsum.photos/seed/auth-16/100/100",
    reviews: [
      { id: "r-23-1", reviewer: "Laura King", text: "My 5-year-old asks for this every single night!", rating: 5, date: "2024-01-11" },
      { id: "r-23-2", reviewer: "Mark Davies", text: "Adorable illustrations and wonderful moral lesson.", rating: 4.8, date: "2024-02-09" },
    ],
  },
  {
    id: "b-24",
    title: "Spanish in 30 Days",
    author: "Mateo Garcia",
    authorId: "auth-17",
    category: "Language Learning",
    brand: "Oxford University Press",
    format: "Paperback",
    price: 450,
    imageUrl: "https://picsum.photos/seed/b-24/200/300",
    stock: 35,
    deliveryDays: 3,
    description: "Accelerated conversational Spanish through daily immersive scenarios and audio-guided drills.",
    tagline: "Speak with confidence from your very first week.",
    tags: ["Spanish", "Fluency", "Grammar"],
    relatedIds: ["b-11", "b-19", "b-25"],
    bestseller: false,
    newLaunch: true,
    sells: 880,
    language: "Spanish / English",
    rating: 4.6,
    authorBio: "Mateo Garcia is a polyglot linguist and language curriculum designer.",
    authorAvatar: "https://picsum.photos/seed/auth-17/100/100",
    reviews: [
      { id: "r-24-1", reviewer: "Carlos Ortiz", text: "Extremely intuitive method. Made rapid progress.", rating: 4.8, date: "2024-03-01" },
      { id: "r-24-2", reviewer: "Rachel Adams", text: "Practical vocab and clear grammar breakdowns.", rating: 4.4, date: "2024-03-06" },
    ],
  },
  {
    id: "b-25",
    title: "Pathways of the Soul",
    author: "Anand Swamy",
    authorId: "auth-18",
    category: "Religion",
    brand: "Oxford University Press",
    format: "Paperback",
    price: 410,
    imageUrl: "https://picsum.photos/seed/b-25/200/300",
    stock: 28,
    deliveryDays: 3,
    description: "Comparative spiritual traditions from ancient Vedic texts to contemporary mindfulness philosophy.",
    tagline: "Many rivers flowing to the same eternal ocean.",
    tags: ["Spirituality", "Meditation", "Vedic"],
    relatedIds: ["b-18", "b-11", "b-26"],
    bestseller: false,
    newLaunch: false,
    sells: 1560,
    language: "English",
    rating: 4.8,
    authorBio: "Anand Swamy is a scholar of comparative theology and Vedic philosophy.",
    authorAvatar: "https://picsum.photos/seed/auth-18/100/100",
    reviews: [
      { id: "r-25-1", reviewer: "Suresh Menon", text: "Deeply illuminating comparative spiritual study.", rating: 5, date: "2024-01-27" },
      { id: "r-25-2", reviewer: "Emma Wilson", text: "Compassionate, insightful, and unifying perspective.", rating: 4.6, date: "2024-02-15" },
    ],
  },
  {
    id: "b-26",
    title: "Chasing Horizons: A Life Untold",
    author: "Victoria Sterling",
    authorId: "auth-19",
    category: "Memoir",
    brand: "Pan Macmillan",
    format: "Hardcover",
    price: 680,
    imageUrl: "https://picsum.photos/seed/b-26/200/300",
    stock: 17,
    deliveryDays: 3,
    description: "An intimate autobiography of an investigative journalist reporting from war zones over three decades.",
    tagline: "Truth is always the most dangerous assignment.",
    tags: ["Journalism", "Courage", "Biography"],
    relatedIds: ["b-27", "b-19", "b-1"],
    bestseller: false,
    newLaunch: false,
    sells: 1890,
    language: "English",
    rating: 4.7,
    authorBio: "Victoria Sterling is a Pulitzer-winning international correspondent.",
    authorAvatar: "https://picsum.photos/seed/auth-19/100/100",
    reviews: [
      { id: "r-26-1", reviewer: "David Frost", text: "Gripping, raw, and deeply inspiring memoir.", rating: 5, date: "2024-01-08" },
      { id: "r-26-2", reviewer: "Claire Bennet", text: "An extraordinary life lived on the front lines.", rating: 4.4, date: "2024-02-12" },
    ],
  },
  {
    id: "b-27",
    title: "The Architect of Modernity",
    author: "Arthur Vance",
    authorId: "auth-20",
    category: "Biography",
    brand: "Penguin Random House",
    format: "Hardcover",
    price: 760,
    imageUrl: "https://picsum.photos/seed/b-27/200/300",
    stock: 14,
    deliveryDays: 4,
    description: "The definitive biography of the visionary engineers who built the 20th century electric grid.",
    tagline: "Powering the modern world from darkness.",
    tags: ["History", "Engineering", "Innovation"],
    relatedIds: ["b-9", "b-17", "b-26"],
    bestseller: false,
    newLaunch: false,
    sells: 1220,
    language: "English",
    rating: 4.6,
    authorBio: "Arthur Vance is a biographer specializing in history of science and technology.",
    authorAvatar: "https://picsum.photos/seed/auth-20/100/100",
    reviews: [
      { id: "r-27-1", reviewer: "Paul Higgins", text: "Fascinating look into industrial geniuses.", rating: 4.7, date: "2024-01-16" },
      { id: "r-27-2", reviewer: "Sarah Vance", text: "Thoroughly documented and riveting story.", rating: 4.5, date: "2024-02-23" },
    ],
  },
  {
    id: "b-28",
    title: "Echoes of the High Peaks",
    author: "Maya Lin",
    authorId: "auth-12",
    category: "Travel",
    brand: "Penguin Random House",
    format: "Hardcover",
    price: 640,
    imageUrl: "https://picsum.photos/seed/b-28/200/300",
    stock: 15,
    deliveryDays: 3,
    description: "A breathtaking photographic and narrative expedition across the Karakoram range.",
    tagline: "Above eight thousand meters, silence is absolute.",
    tags: ["Mountains", "Photography", "K2"],
    relatedIds: ["b-19", "b-4", "b-10"],
    bestseller: false,
    newLaunch: true,
    sells: 510,
    language: "English",
    rating: 4.8,
    authorBio: "Maya Lin is a travel photographer, explorer, and mountaineer.",
    authorAvatar: "https://picsum.photos/seed/auth-12/100/100",
    reviews: [
      { id: "r-28-1", reviewer: "James Cole", text: "Stunning photographs and harrowing mountain stories.", rating: 5, date: "2024-03-03" },
      { id: "r-28-2", reviewer: "Leila Ortiz", text: "A masterpiece of expedition storytelling.", rating: 4.6, date: "2024-03-08" },
    ],
  },
  {
    id: "b-29",
    title: "Labyrinth of the Mind",
    author: "Dr. Aris Thorne",
    authorId: "auth-7",
    category: "Science",
    brand: "Oxford University Press",
    format: "Paperback",
    price: 520,
    imageUrl: "https://picsum.photos/seed/b-29/200/300",
    stock: 24,
    deliveryDays: 2,
    description: "Unraveling memory, subconscious cognition, and how sleep reconstructs our waking brain.",
    tagline: "The three pounds that dream the cosmos.",
    tags: ["Brain", "Neuroscience", "Sleep"],
    relatedIds: ["b-11", "b-12", "b-17"],
    bestseller: false,
    newLaunch: false,
    sells: 2100,
    language: "English",
    rating: 4.7,
    authorBio: "Dr. Aris Thorne is a cognitive psychologist and behavioral researcher.",
    authorAvatar: "https://picsum.photos/seed/auth-7/100/100",
    reviews: [
      { id: "r-29-1", reviewer: "Simon Pegg", text: "Fascinating neurobiology made accessible.", rating: 5, date: "2024-01-21" },
      { id: "r-29-2", reviewer: "Alicia Keys", text: "Helped me understand sleep hygiene and brain plasticity.", rating: 4.4, date: "2024-02-18" },
    ],
  },
  {
    id: "b-30",
    title: "Dawn on the Danube",
    author: "Eleanor Vance",
    authorId: "auth-1",
    category: "Mystery",
    brand: "Pan Macmillan",
    format: "Hardcover",
    price: 610,
    imageUrl: "https://picsum.photos/seed/b-30/200/300",
    stock: 20,
    deliveryDays: 3,
    description: "An art appraiser finds a missing Renaissance portrait tied to an unsolved murder on a luxury river cruise.",
    tagline: "Blood runs deeper than the Danube.",
    tags: ["Art Theft", "River Cruise", "Detective"],
    relatedIds: ["b-1", "b-2", "b-4"],
    bestseller: false,
    newLaunch: true,
    sells: 690,
    language: "English",
    rating: 4.6,
    authorBio: "Eleanor Vance is a bestselling crime novelist based in Edinburgh.",
    authorAvatar: "https://picsum.photos/seed/auth-1/100/100",
    reviews: [
      { id: "r-30-1", reviewer: "Arthur Dent", text: "Delightful European murder mystery with wonderful setting.", rating: 4.8, date: "2024-03-04" },
      { id: "r-30-2", reviewer: "Bethany Cruz", text: "Richly detailed art history trivia mixed with high stakes.", rating: 4.4, date: "2024-03-09" },
    ],
  },
];

const defaultPasswordHash = bcryptjs.hashSync("password123", 10);

export const users: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "prosenjit.mondal@ibm.com",
    passwordHash: defaultPasswordHash,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    passwordHash: defaultPasswordHash,
  },
  {
    id: "3",
    name: "Alex Rivera",
    email: "alex@example.com",
    passwordHash: defaultPasswordHash,
  },
];

export const addresses: Address[] = [
  {
    id: "addr-1",
    userId: "1",
    firstName: "John",
    lastName: "Doe",
    addressLine: "123 MG Road, Flat 4B",
    email: "john@example.com",
    city: "Bengaluru",
    pin: "560001",
    phone: "9876543210",
    state: "Karnataka",
    country: "India",
  },
  {
    id: "addr-2",
    userId: "1",
    firstName: "John",
    lastName: "Doe",
    addressLine: "45 Brigade Towers, Residency Road",
    email: "john@example.com",
    city: "Bengaluru",
    pin: "560025",
    phone: "9876543210",
    state: "Karnataka",
    country: "India",
  },
  {
    id: "addr-3",
    userId: "2",
    firstName: "Jane",
    lastName: "Smith",
    addressLine: "74 Park Street, Suite 12",
    email: "jane@example.com",
    city: "Kolkata",
    pin: "700016",
    phone: "9123456780",
    state: "West Bengal",
    country: "India",
  },
  {
    id: "addr-4",
    userId: "2",
    firstName: "Jane",
    lastName: "Smith",
    addressLine: "88 Salt Lake Sector V",
    email: "jane@example.com",
    city: "Kolkata",
    pin: "700091",
    phone: "9123456780",
    state: "West Bengal",
    country: "India",
  },
  {
    id: "addr-5",
    userId: "3",
    firstName: "Alex",
    lastName: "Rivera",
    addressLine: "12 Marine Drive, Sea Breeze Apts",
    email: "alex@example.com",
    city: "Mumbai",
    pin: "400020",
    phone: "9811223344",
    state: "Maharashtra",
    country: "India",
  },
  {
    id: "addr-6",
    userId: "3",
    firstName: "Alex",
    lastName: "Rivera",
    addressLine: "502 Bandra Kurla Complex, Tower B",
    email: "alex@example.com",
    city: "Mumbai",
    pin: "400051",
    phone: "9811223344",
    state: "Maharashtra",
    country: "India",
  },
];

export const giftPoints: GiftPoints[] = [
  { userId: "1", points: 200 },
  { userId: "2", points: 200 },
  { userId: "3", points: 200 },
];
